alter table public.products
  add column if not exists formal_product_name text,
  add column if not exists product_name_kana text,
  add column if not exists manufacturer_code text,
  add column if not exists manufacturer_name text,
  add column if not exists reference_retail_price numeric(12, 2),
  add column if not exists purchase_lot_quantity numeric(12, 2),
  add column if not exists sales_lot_quantity numeric(12, 2),
  add column if not exists minimum_order_unit text,
  add column if not exists case_gtin text,
  add column if not exists unit_width_mm numeric(12, 2),
  add column if not exists unit_height_mm numeric(12, 2),
  add column if not exists unit_depth_mm numeric(12, 2),
  add column if not exists unit_volume_l numeric(12, 3),
  add column if not exists unit_weight_g numeric(12, 2),
  add column if not exists case_width_mm numeric(12, 2),
  add column if not exists case_height_mm numeric(12, 2),
  add column if not exists case_depth_mm numeric(12, 2),
  add column if not exists case_volume_l numeric(12, 3),
  add column if not exists case_weight_g numeric(12, 2),
  add column if not exists receipt_product_name text,
  add column if not exists product_weight text,
  add column if not exists product_features text,
  add column if not exists product_catchcopy text,
  add column if not exists usage_instructions text,
  add column if not exists ingredients text,
  add column if not exists country_of_origin text,
  add column if not exists shelf_life_days text,
  add column if not exists hazardous_material_category text;
